# Site Configuration
title: "HackWell Blog"
description: "Cybersecurity writeups, research, and learning resources"
author: "HackWell"
email: "contact@hackwell.com"
url: "https://hakwell.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "HackWell"

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "HackTheBox"
    url: "/posts/hackthebox/"
  - title: "TryHackMe"
    url: "/posts/tryhackme/"
  - title: "OffSec"
    url: "/posts/offsec/"

# Social links
social:
  - name: "GitHub"
    url: "https://github.com/hackwell"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/hackwell"
  - name: "Twitter"
    url: "https://twitter.com/hackwell"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include in processing
include:
  - _pages

# Kramdown configuration
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
